---
- name: Iniciar JBoss como proceso en segundo plano
  hosts: all
  gather_facts: no

  tasks:
    - name: Iniciar JBoss en segundo plano con PowerShell
      win_shell: |
        Start-Process powershell -ArgumentList '-NoProfile -WindowStyle Hidden -Command "Start-Process -FilePath ''C:\jboss-eap-7.4.0\jboss-eap-7.4\bin\standalone.bat'' -WorkingDirectory ''C:\jboss-eap-7.4.0\jboss-eap-7.4\bin''"' -WindowStyle Hidden
