---
- name: Iniciar JBoss como proceso independiente con PowerShell
  hosts: all
  gather_facts: no

  tasks:
    - name: Iniciar JBoss con PowerShell
      win_shell: >
        powershell.exe -Command "Start-Process -FilePath 'standalone.bat' -WorkingDirectory 'C:\jboss-eap-7.4.0\jboss-eap-7.4\bin' -WindowStyle Hidden"
