---
- name: Iniciar JBoss como proceso en segundo plano
  hosts: all
  gather_facts: no
  tasks:
    - name: Iniciar JBoss con start
      win_command: 'cmd /c start "" "C:\jboss-eap-7.4.0\jboss-eap-7.4\bin\standalone.bat"'
      args:
        chdir: 'C:\jboss-eap-7.4.0\jboss-eap-7.4\bin'
